config/routes.rb
FunFinder::Application.routes.draw do
  
  root to: "home#index"
  
  get "/sign-up", to: "users#new", as: :sign_up
  post "/sign-up", to: "users#create"
  get "/sign-in", to: "sessions#new", as: :sign_in
  post "/sign-in", to: "sessions#create"
  get "/search", to: "search#create", as: :search
  get "/user", to: "users#show", as: :user
  
  resources :events, only: [:index, :new, :create, :edit, :update, :destroy], path: "my-events"
  resources :events, only: [:show]
  resources :calendar, only: [:index]
  
  namespace :admin do
    resources :events, only: [:index, :show, :edit, :update]
  end
  
end

app/models/event.rb
class Event
  
  attr_accessor :day_string
  
  include Mongoid::Document
  include Mongoid::Timestamps
  
  field :user_id, type: Integer
  field :name, type: String
  field :day, type: Date
  field :hour, type: String
  field :description, type: String
  field :url, type: String
  field :address, type: String
  field :address_complement, type: String
  field :zip_code, type: String
  field :latitude, type: Float
  field :longitude, type: Float
  
  field :benefit_description, type: String
  field :benefit_approved, type: Boolean, default: false
  
  field :location, type: Array
  index({location: "2d"})
  
  belongs_to :user
  
  validates :user, :name, :day, :hour, :description, :address, :zip_code, :latitude, :longitude, presence: true
  validates :name, length: { in: 15..100 }
  validates :description, length: { in: 50..400 }
  
  after_initialize :date_from_string
  before_validation :date_from_string
  after_find :string_from_date
  
  before_validation :set_location
  
  scope :search, lambda { |terms|
    any_of({:name => /.*#{terms.gsub(/\s/, ".+")}.*/i})
  }
  
  scope :nearby, lambda { |lat, lng|
    # where(
    #   latitude: {"$lte" => lat + 0.12, "$gte" => lat - 0.12},
    #   longitude: {"$lte" => lng + 0.12, "$gte" => lng - 0.12}
    # )
    # near_sphere(location: [ lat, lng ]).max_distance(location: 1)
    within_circle(
      location: [[ lat, lng ], 0.1 ]
    )
  }
  
  scope :for_week, lambda { |beginning_of_week, end_of_week|
    where(:day.gte => beginning_of_week).where(:day.lte => end_of_week)
  }
  
  scope :for_future, lambda {
    where(:day.gte => DateTime.current)
  }
  
  scope :benefits_to_approve, lambda {
    where(:benefit_description.ne => "", :benefit_description.exists => true, benefit_approved: false)
  }
  
  def full_address
    "#{address} #{' - ' + address_complement if address_complement.present?}"
  end
  
  def month_string
    I18n.l day, format: :month_string
  end
  
  def has_benefit?
    benefit_description.present?
  end
  
  def should_approve_benefit?
    has_benefit? && !benefit_approved
  end
    
  protected
  
  def date_from_string
    self.day = Time.parse("#{day_string}", "%d/%m/%Y") if day_string.present?
  end
  
  def string_from_date
    self.day_string = day.strftime("%d/%m/%Y")
  end
  
  def set_location
    self.location = [latitude, longitude]
  end
  
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < Admin::AdminController
    
  before_action :load_event, only: [:edit, :update]
    
  def index
    @events = Event.scoped
    @events = @events.search(params[:search]) if params[:search].present?
    @events = @events.for_future unless params[:past].present?
    @events = @events.benefits_to_approve if params[:pendent].present?
    @events = @events.paginate(page: params[:page], per_page: 20)
  end
  
  def edit
    render layout: false
  end
  
  def update
  end
  
  protected
  
  def load_event
    @event = Event.find(params[:id])
  end
  
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  
  before_action :authenticate_user!, only: [:index, :new, :create, :edit, :update, :destroy]
  before_action :load_event, only: [:edit, :update, :destroy]
  
  def index
    @page_title = "Meus Eventos"
    @events = current_user.events.asc(:day, :hour).paginate(page: params[:page], per_page: 5)
  end
  
  def show
    @event = Event.find(params[:id])
    respond_to do |format|
      format.html {
        render layout: false
      }
      format.json {
        render json: @event.to_json(methods: :month_string)
      }
    end
    
  end
  
  def new
    @page_title = "Novo Evento"
    @event = current_user.events.new
    render layout: false
  end
  
  def create
    @event = current_user.events.new(event_params)
    @event.save
    respond_to do |format|
      format.js
      format.html {
        @page_title = "Novo Evento"
        if @event.persisted?
          redirect_to events_path
        else
          render :new, layout: false
        end
      }
    end
    
  end
  
  def edit
    @page_title = "Editar Evento"
    render layout: false
  end
  
  def update
    @event.update(event_params)
    respond_to do |format|
      format.js
    end
  end
  
  def destroy
    @event.destroy
    redirect_to events_path
  end
  
  protected
  
  def event_params
    params.require(:event).permit(:user_id, :address, :address_complement, :name, :day_string, :hour, :url, :latitude, :longitude, :description, :zip_code, :benefit_description)
  end
  
  def load_event
    @event = current_user.events.find(params[:id])
  end
  
end

app/helpers/events_helper.rb
module EventsHelper
  
  def textile(text)
    RedCloth.new(text).to_html.html_safe
  end
  
  def url_params(start_date)
    {
      address: params[:address],
      latitude: params[:latitude],
      longitude: params[:longitude],
      start_date: start_date
    }
  end
  
end

app/views/admin/events/index.html.erb
<div class="events clearfix">
  <div class="row">
    <div class="col-xs-12">
      <div class="page-header clearfix">
        <div class="btn-group pull-left">
          <%= link_to icon_tag("glyphicon-arrow-left") + "Voltar ao Site", root_path, class: "btn btn-default btn-sm" %>
          <%= link_to "Olá #{current_user.name}", "#", class: "btn btn-default btn-sm disabled" %>
        </div>
        <h1>Eventos</h1>
        <div class="btn-group pull-left">
          <%= link_to "Eventos Passados", admin_events_path(past: true), class: "btn btn-default btn-sm" %>
          <%= link_to icon_tag("glyphicon-asterisk", "Benefícios Pendentes"), admin_events_path(pendent: true), class: "btn btn-default btn-sm btn-danger" %>
        </div>
        <div class="form-group pull-left">
          <%= form_tag admin_events_path, method: :get do %>
            <%= text_field_tag :search, params[:search], class: "form-control input-sm", placeholder: "Buscar Eventos", autocomplete: "off" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12">
      <div class="list">
        <table class="table table-hover">
          <thead>
            <tr>
              <th>Nome do Evento</th>
              <th width="5"></th>
              <th width="5"></th>
              <th>Usuário</th>
              <th>Data</th>
              <th>Hora</th>
              <th></th>
              <th width="10"></th>
            </tr>
          </thead>
          <tbody>
            <% @events.each do |event| %>
              <tr>
                <td><%= link_to truncate(event.name, length: 50), edit_admin_event_path(event), class: "ordinary-link admin-lightbox-event-click" %></td>
                <td>
                  <%= form_for [:admin, event], remote: true do |f| %>
                    <%= f.hidden_field :benefit_approved, value: true %>
                    <%= link_to icon_tag("glyphicon-ok"), "javascript:$(this).parent().submit()", class: "btn text-success" %>
                  <% end if event.should_approve_benefit? %>
                </td>
                <td>
                  <% if event.should_approve_benefit? %>
                    <%= link_to "javascript:void(0)", rel: "popover", data: {content: "#{event.benefit_description}", placement: "top" } do %>
                      <%= content_tag :span, icon_tag("glyphicon-asterisk"), class: "text-danger" %>
                    <% end %>
                  <% end %>
                </td>
                <td><%= link_to event.user.name, "#", rel: "popover", data: { content: "#{event.user.email}<br /><small>#{I18n.l event.user.created_at, format: :short}</small>", placement: "top" } %></td>
                <td><%= I18n.l event.day %></td>
                <td><%= event.hour %></td>
                <td>
                  <%= link_to icon_tag("glyphicon-map-marker"), "javascript:void(0)", rel: "popover", data: { content: "#{event.full_address}", placement: "left" }, class: "btn" %>
                  <%= link_to icon_tag("glyphicon-info-sign"), "javascript:void(0)", rel: "popover", data: { content: "#{event.description}", placement: "left" }, class: "btn" %>
                </td>
                <td>
                  <%= link_to icon_tag("glyphicon-trash"), admin_event_path(event), class: "btn text-danger", rel: "popover", method: :delete, data: { confirm: "Você tem certeza que dedeja excluir o evento de #{event.name}?", content: "Excluir Evento", placement: "left" } %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <%= will_paginate @events %>
      </div>
    </div>
  </div>
</div>