config/routes.rb
FunFinder::Application.routes.draw do
  
  root to: "home#index"
  
  get "/sign-up", to: "users#new", as: :sign_up
  post "/sign-up", to: "users#create"
  get "/sign-in", to: "sessions#new", as: :sign_in
  post "/sign-in", to: "sessions#create"
  get "/search", to: "search#create", as: :search
  get "/user", to: "users#show", as: :user
  
  resources :events, only: [:index, :new, :create, :edit, :update, :destroy], path: "my-events"
  resources :events, only: [:show]
  resources :calendar, only: [:index]
  
  namespace :admin do
    resources :events, only: [:index, :show, :edit, :update]
  end
  
end

app/models/search.rb
class Search
  
  attr_accessor :address
  attr_reader :latitude, :longitude
  
  def initialize(latitude, longitude)
    @latitude = latitude.to_f
    @longitude = longitude.to_f
  end
  
  def events(beginning_of_week, end_of_week)
    Event.for_week(beginning_of_week, end_of_week).asc(:day, :hour).nearby(@latitude, @longitude).group_by(&:day)
  end
  
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  
  before_action :load_week
  
  def create
    @page_title = "Encontre a boa em #{params[:address]}"
    @search = Search.new(params[:latitude], params[:longitude])
    @events = @search.events(@beginning_of_week, @end_of_week)
  end
  
  protected
  
  def load_week
    @beginning_of_week = Date.parse(params[:start_date]) if params[:start_date].present?
    @beginning_of_week ||= DateTime.current.beginning_of_week(:sunday).to_date
    @end_of_week = @beginning_of_week + 6.days
  end
  
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/search/_event.html.erb
<div class="panel panel-default" data-lat="<%= event.latitude %>" data-lng="<%= event.longitude %>" data-id="<%= event.id %>">
  <div class="panel-heading">
    <h4 class="panel-title">
      <small><%= I18n.l event.day, format: :complete %> às <%= event.hour %></small>
      <%= link_to event.name, "#collapse-#{event.id}", data: { toggle: "collapse", parent: "#events-accordion" } %>
    </h4>
  </div>
  <div id="collapse-<%= event.id %>" class="panel-collapse collapse">
    <div class="panel-body">
      <div class="address"><%= event.full_address %></div>
      <div class="content">
        <%= textile(event.description) %>
      </div>
      <% if event.url.present? %>
        <div class="url">
          <%= link_to "Site do evento ".html_safe + icon_tag("glyphicon-new-window"), event.url, target: :blank, title: "Site do evento #{j event.name}", class: "btn btn-default btn-xs" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/search/create.html.erb
<div class="search">
<div class="row">
  <!-- <div class="col-sm-4 col-xs-12 hidden-xs sidebar">
    <h3><%= icon_tag("glyphicon-map-marker") %> Buscar em</h3>
  </div> -->
  <div class="col-sm-12 col-xs-12 hidden-xs main-events">
    <h2 class="pull-left"><%= icon_tag("glyphicon-calendar") %>
      Eventos da semana <strong><%= I18n.l @beginning_of_week, format: :day_month %> - <%= I18n.l @end_of_week, format: :day_month %></strong>
    </h2>
    <div class="btn-group pull-right">
      <%= link_to icon_tag("glyphicon-arrow-left") + " Anterior".html_safe, search_path(url_params(@beginning_of_week - 7.days)), class: "btn btn-default btn-xs" %>
      <%= link_to "Próxima ".html_safe + icon_tag("glyphicon-arrow-right"), search_path(url_params(@end_of_week + 1.days)), class: "btn btn-default btn-xs" %>
    </div>
    <div class="clearfix"></div>
    <div class="table-events-support">
      <!--
      <%= link_to icon_tag("glyphicon-circle-arrow-left"), "#", class: "click-arrow left", data: { direction: "left"} %>
      <%= link_to icon_tag("glyphicon-circle-arrow-right"), "#", class: "click-arrow right", data: { direction: "right"} %>
      -->
      <table class="table table-events pos1">
        <tr>
          <% (@beginning_of_week..@end_of_week).each do |day| %>
            <th><%= I18n.l day, format: :week_day %></th>
          <% end %>
        </tr>
        <tr>
          <% (@beginning_of_week..@end_of_week).each do |day| %>
            <td>
              <ul>
                <% @events[day].each do |event| %>
                  <li data-lat="<%= event.latitude %>" data-lng="<%= event.longitude %>" data-id="<%= event.id %>">
                    <%= link_to "##{event.id}", rel: "nofollow" do %>
                      <small><%= event.hour %></small>
                      <%= event.name %>
                    <% end %>
                  </li>
                <% end if @events[day] %>
              </ul>
            </td>
          <% end %>
        </tr>
      </table>
    </div>
    
  </div>
</div>
</div>
<%= content_for :unwrap_content do %>
  <div class="search-header clearfix">
    <div class="container">
      <div class="row">
        <div class="col-sm-12">
          <h1><%= link_to "Encontre a Boa <small>beta</small>".html_safe, root_path%></h1>
          <p class="lead"><%= params[:address] %></p>
          <!--
          <%= link_to "Fazer Login", sign_in_path, class: "btn pull-right" %>
          <%= link_to "Divulgue seu evento", sign_up_path, class: "btn pull-right" %>
          -->
        </div>
      </div>
      <!--
      <div class="row">
        <div class="col-sm-12">
          <div class="search-field clearfix">
            <div class="form-group">
              <%= label_tag :q, "Onde você está?", class: "sr-only" %>
              <%= text_field_tag :q, params[:address], class: "form-control input-lg", placeholder: "Onde você está ou quer ir?", autocomplete: "off" %>
            </div>
          </div>
        </div>
      </div>
      -->  
    </div>
  </div>
  <div id="google_map_search" class="google-map-canvas-fullscreen" data-latitude="<%= @search.latitude %>" data-longitude="<%= @search.longitude %>"></div>
  <div class="expand-map">
    <%= icon_tag("glyphicon-chevron-down") %>
  </div>
<% end %>