config/routes.rb
FunFinder::Application.routes.draw do
  
  root to: "home#index"
  
  get "/sign-up", to: "users#new", as: :sign_up
  post "/sign-up", to: "users#create"
  get "/sign-in", to: "sessions#new", as: :sign_in
  post "/sign-in", to: "sessions#create"
  get "/search", to: "search#create", as: :search
  get "/user", to: "users#show", as: :user
  
  resources :events, only: [:index, :new, :create, :edit, :update, :destroy], path: "my-events"
  resources :events, only: [:show]
  resources :calendar, only: [:index]
  
  namespace :admin do
    resources :events, only: [:index, :show, :edit, :update]
  end
  
end

app/views/shared/_dashboard_sidebar.html.erb
<ul class="nav nav-pills nav-stacked">
  <li><%= link_to icon_tag("glyphicon-plus", "Criar Evento"), new_event_path, class: "active lightbox-event-click" %></li>
  <!-- <li><%= link_to icon_tag("glyphicon-cog", "Configurações"), "#" %></li> -->
</ul>
<div class="my-calendar">
</div>

app/views/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div class="alert alert-warning">
    <a href="#" class="close" data-dismiss="alert">&times;</a>
    <%= resource.errors.full_messages.join(", ") %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="container clearfix">
    <p class="text-muted about pull-left">Quer divulgar seu evento? <%= link_to "Crie uma conta", sign_up_path %> agora mesmo.</p>
    <div class="nav pull-right">
      <%= link_to "Buscar boa!", root_path %>
    </div>
  </div>
</div>