config/routes.rb
FunFinder::Application.routes.draw do
  
  root to: "home#index"
  
  get "/sign-up", to: "users#new", as: :sign_up
  post "/sign-up", to: "users#create"
  get "/sign-in", to: "sessions#new", as: :sign_in
  post "/sign-in", to: "sessions#create"
  get "/search", to: "search#create", as: :search
  get "/user", to: "users#show", as: :user
  
  resources :events, only: [:index, :new, :create, :edit, :update, :destroy], path: "my-events"
  resources :events, only: [:show]
  resources :calendar, only: [:index]
  
  namespace :admin do
    resources :events, only: [:index, :show, :edit, :update]
  end
  
end

app/models/event.rb
class Event
  
  attr_accessor :day_string
  
  include Mongoid::Document
  include Mongoid::Timestamps
  
  field :user_id, type: Integer
  field :name, type: String
  field :day, type: Date
  field :hour, type: String
  field :description, type: String
  field :url, type: String
  field :address, type: String
  field :address_complement, type: String
  field :zip_code, type: String
  field :latitude, type: Float
  field :longitude, type: Float
  
  field :benefit_description, type: String
  field :benefit_approved, type: Boolean, default: false
  
  field :location, type: Array
  index({location: "2d"})
  
  belongs_to :user
  
  validates :user, :name, :day, :hour, :description, :address, :zip_code, :latitude, :longitude, presence: true
  validates :name, length: { in: 15..100 }
  validates :description, length: { in: 50..400 }
  
  after_initialize :date_from_string
  before_validation :date_from_string
  after_find :string_from_date
  
  before_validation :set_location
  
  scope :search, lambda { |terms|
    any_of({:name => /.*#{terms.gsub(/\s/, ".+")}.*/i})
  }
  
  scope :nearby, lambda { |lat, lng|
    # where(
    #   latitude: {"$lte" => lat + 0.12, "$gte" => lat - 0.12},
    #   longitude: {"$lte" => lng + 0.12, "$gte" => lng - 0.12}
    # )
    # near_sphere(location: [ lat, lng ]).max_distance(location: 1)
    within_circle(
      location: [[ lat, lng ], 0.1 ]
    )
  }
  
  scope :for_week, lambda { |beginning_of_week, end_of_week|
    where(:day.gte => beginning_of_week).where(:day.lte => end_of_week)
  }
  
  scope :for_future, lambda {
    where(:day.gte => DateTime.current)
  }
  
  scope :benefits_to_approve, lambda {
    where(:benefit_description.ne => "", :benefit_description.exists => true, benefit_approved: false)
  }
  
  def full_address
    "#{address} #{' - ' + address_complement if address_complement.present?}"
  end
  
  def month_string
    I18n.l day, format: :month_string
  end
  
  def has_benefit?
    benefit_description.present?
  end
  
  def should_approve_benefit?
    has_benefit? && !benefit_approved
  end
    
  protected
  
  def date_from_string
    self.day = Time.parse("#{day_string}", "%d/%m/%Y") if day_string.present?
  end
  
  def string_from_date
    self.day_string = day.strftime("%d/%m/%Y")
  end
  
  def set_location
    self.location = [latitude, longitude]
  end
  
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < Admin::AdminController
    
  before_action :load_event, only: [:edit, :update]
    
  def index
    @events = Event.scoped
    @events = @events.search(params[:search]) if params[:search].present?
    @events = @events.for_future unless params[:past].present?
    @events = @events.benefits_to_approve if params[:pendent].present?
    @events = @events.paginate(page: params[:page], per_page: 20)
  end
  
  def edit
    render layout: false
  end
  
  def update
  end
  
  protected
  
  def load_event
    @event = Event.find(params[:id])
  end
  
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  
  before_action :authenticate_user!, only: [:index, :new, :create, :edit, :update, :destroy]
  before_action :load_event, only: [:edit, :update, :destroy]
  
  def index
    @page_title = "Meus Eventos"
    @events = current_user.events.asc(:day, :hour).paginate(page: params[:page], per_page: 5)
  end
  
  def show
    @event = Event.find(params[:id])
    respond_to do |format|
      format.html {
        render layout: false
      }
      format.json {
        render json: @event.to_json(methods: :month_string)
      }
    end
    
  end
  
  def new
    @page_title = "Novo Evento"
    @event = current_user.events.new
    render layout: false
  end
  
  def create
    @event = current_user.events.new(event_params)
    @event.save
    respond_to do |format|
      format.js
      format.html {
        @page_title = "Novo Evento"
        if @event.persisted?
          redirect_to events_path
        else
          render :new, layout: false
        end
      }
    end
    
  end
  
  def edit
    @page_title = "Editar Evento"
    render layout: false
  end
  
  def update
    @event.update(event_params)
    respond_to do |format|
      format.js
    end
  end
  
  def destroy
    @event.destroy
    redirect_to events_path
  end
  
  protected
  
  def event_params
    params.require(:event).permit(:user_id, :address, :address_complement, :name, :day_string, :hour, :url, :latitude, :longitude, :description, :zip_code, :benefit_description)
  end
  
  def load_event
    @event = current_user.events.find(params[:id])
  end
  
end

app/helpers/events_helper.rb
module EventsHelper
  
  def textile(text)
    RedCloth.new(text).to_html.html_safe
  end
  
  def url_params(start_date)
    {
      address: params[:address],
      latitude: params[:latitude],
      longitude: params[:longitude],
      start_date: start_date
    }
  end
  
end

app/views/events/_events_table.html.erb
<table class="table">
  <thead>
    <tr>
      <th>Nome do Evento</th>
      <th>Data</th>
      <th>Hora</th>
      <th>Endereço</th>
      <th width="10"></th>
    </tr>
  </thead>
  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= link_to truncate(event.name, length: 50), edit_event_path(event), class: "lightbox-event-click ordinary-link" %></td>
        <td><%= I18n.l event.day %></td>
        <td><%= event.hour %></td>
        <td><%= truncate event.full_address, length: 30 %></td>
        <td>
          <%= link_to icon_tag("glyphicon-trash"), event_path(event), class: "btn text-danger", method: :delete, data: { confirm: "Você tem certeza que dedeja excluir o evento de #{event.name}?" } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/events/_form.html.erb
<%= form_for @event, url: (@event.persisted? ? event_path(@event) : events_path), html: { role: "form", data: { remote: true}} do |f| %>
  
  <div class="slides">
    
    <a href="#" class="click-arrow left disabled"><%= icon_tag("glyphicon-chevron-left") %></a>
    <a href="#" class="click-arrow right"><%= icon_tag("glyphicon-chevron-right") %></a>
    <button type="submit" class="submit-slides"><%= icon_tag("glyphicon-ok") %></button>
    
    <div class="slides-inner clearfix">
      
      <div class="slide where" data-inner="600,400" data-pos="0">
        <h2>Onde será o evento?</h2>
        <div class="spacing">
          <div class="row">
            <div class="form-group col-sm-6">
              <%= f.label :address %>
              <%= f.text_field :address, class: "form-control", placeholder: "Mapa atualizará automaticamente" %>
            </div>
            <div class="form-group col-sm-3">
              <%= f.label :address_complement %>
              <%= f.text_field :address_complement, class: "form-control" %>
            </div>
            <div class="form-group col-sm-3">
              <%= f.label :zip_code %>
              <%= f.text_field :zip_code, class: "form-control" %>
            </div>
          </div>
          <div class="form-group">
            <div id="google_map" class="google-map-canvas"></div>
            <%= f.hidden_field :latitude %>
            <%= f.hidden_field :longitude %>
          </div>
        </div>
        
      </div><!-- .slide 0 -->
      
      <div class="slide other" data-inner="400,200" data-pos="1">
        <h2>Benefício do Anúncio
          <small>Você pode dar um benefício para seus clientes e em troca<br /> ter informações
            sobre seu público</small>
        </h2>
        <div class="spacing">
          <div class="row">
            <div class="col-sm-8">
              <div class="form-group">
                <%= f.text_area :benefit_description, class: "form-control", rows: 11, placeholder: "Descrição do Benefício" %>
              </div>
            </div>
            <div class="col-sm-4">
              <small class="text-muted">Todo usuário que quiser utilizar o benefício terá que conectar usando o Facebook
              e fornecer alguns dados que serão utilizados para gerar um relatório sobre seu público.
              <strong>Seu benefício será aprovado por um de nossos redatores em até 48 horas</strong>.</small>
            </div>
          </div>
        </div>
      </div> <!-- .slide1 -->
      
      <div class="slide other" data-inner="400,200" data-pos="2">
        <h2><%= @event.persisted? ? "Editar informações" : "Só falta mais esse passo" %></h2>
        <div class="spacing">
          <div class="row">
            <div class="col-sm-12">
              <div class="form-group">
                <%= f.label :name %>
                <%= f.text_field :name, class: "form-control", placeholder: "Exibido na listagem de eventos." %>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="form-group col-sm-4">
              <%= f.label :day %>
              <%= f.text_field :day_string, class: "form-control" %>
            </div>
            <div class="form-group col-sm-2">
              <%= f.label :hour %>
              <%= f.text_field :hour, class: "form-control" %>
            </div>
            <div class="col-sm-6">
              <div class="form-group">
                <%= f.label :url %>
                <%= f.text_field :url, class: "form-control", placeholder: "" %>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-sm-12">
              <div class="form-group">
                <%= f.text_area :description, class: "form-control", rows: 5, placeholder: "Informe os detalhes do seu evento." %>
                <small>Você pode usar o padrão textile para formatar os detalhes do evento. Veja <%= link_to "aqui", "#" %> como funciona.</small>
              </div>
            </div>
          </div>
        </div><!-- .spacing -->
      </div><!-- .slide -->
      
    </div><!-- .slides -->
  </div>
  
<% end %>

app/views/events/create.js.erb
<% if @event.persisted? %>
  window.location.reload();
<% else %>
  alert("<%= j @event.errors.full_messages.join(', ') %>")
<% end %>

app/views/events/edit.html.erb
<div class="lightbox-container">
  <%= render "form" %>
</div>

app/views/events/index.html.erb
<div class="events clearfix">
  <div class="row">
    <div class="col-xs-12">
      <div class="page-header clearfix">
        <h1>Meus Eventos</h1>
        <p class="lead">Gerencie seus eventos e compartilhe com todo mundo.</p>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-3 sidebar">
      <%= render "shared/dashboard_sidebar" %>
    </div>
    <div class="col-sm-9">
      <div class="list">
        <% if @events.any? %>
          <%= render "events_table" %>
          <%= will_paginate @events %>
        <% else %>
          <%= content_for :bottom do %>
            <script type="text/javascript" charset="utf-8">
              $(function(){
                $(".lightbox-event-click").popover({
                  content: "Clique em <strong>Criar Evento</strong> para cadastrar seu primeiro evento",
                  html: true,
                  placement: "right",
                  title: "",
                  container: "body"
                });
                $(".lightbox-event-click").trigger("click");
              });
            </script>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/events/new.html.erb
<div class="lightbox-container">
  <%= render "form" %>
</div>

app/views/events/show.html.erb
<div class="lightbox-container">
  <div class="left info">
    <h2><%= @event.name %></h2>
    <div class="date"><%= I18n.l @event.day, format: :complete %></div>
    <div class="address"><%= @event.full_address %></div>    
    <div class="actions clearfix">
      <%= link_to icon_tag("glyphicon-print"), "#", rel: "popover", title: "", data: { content: "Imprimir" } %>
      <%= link_to icon_tag("glyphicon-home"), "#", rel: "popover", title: "", data: { content: "Visitar Site" } %>
      <%= link_to icon_tag("glyphicon-share-alt"), "#", rel: "popover", title: "", data: { content: "Compartilhar" } %>
    </div>
    <div class="description">
      <%= textile(@event.description) %>
    </div>
  </div>
  <div class="right map">
    <div id="<%= "#{@event.id}_map" %>" class="map"></div>
  </div>
</div>

app/views/events/update.js.erb
<% if @event.changed? %>
  <% if @event.valid? %>
    window.location.reload();
  <% else %>
    alert("<%= j @event.errors.full_messages.join(', ') %>")
  <% end %>
<% else %>
  $.colorbox.close();
<% end %>